# Q1.Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [1]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings("ignore")
import time
import keyboard

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

In [2]:
driver = webdriver.Chrome()
driver.get("https://www.amazon.in/")
driver.maximize_window()

In [3]:
try:
    time.sleep(2)
    click=driver.find_element(By.XPATH,'//*[@id="nav-search-bar-form"]')
    click.click()
except:
    try:
        click=driver.find_element(By.XPATH,'//*[@id="nav-bb-search"]')
        click.click()
    except:
        print("refresh manually")

In [4]:
user_keyword = input("enter the item name to search:" )
user_input=driver.find_element(By.XPATH,'//*[@id="twotabsearchtextbox"]')
user_input.send_keys(user_keyword)

enter the item name to search:guitar

In [5]:
click=driver.find_element(By.XPATH,'//*[@id="nav-search-submit-button"]')
click.click()

# Q2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. 

Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. 

In case, if any of the details are missing for any of the product then replace it by “-“.

In [6]:
Brand_Name = []
Name_of_Product=[]
Ratings=[]
Price = []
Return_Exchange = []
Expected_Delivery = []
Availability = []
Product_URL = []

In [7]:
pages=[]
start=0
end=3

for page in range(start,end):
    page=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in page:
        pages.append(i.get_attribute('href'))

next_page=driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
next_page.click()
len(pages)

180

In [8]:
for i in pages:
    driver.get(i)
    time.sleep(1)

    try:
        brand=driver.find_element(By.XPATH,'//tr[@class="a-spacing-small po-brand"]')
        Brand_Name.append(brand.text.split()[1])

    except:
        Brand_Name.append('-')
        
    try:
        NOP=driver.find_element(By.XPATH,'//span[@class="a-size-large product-title-word-break"]')
        Name_of_Product.append(NOP.text)

    except:
        Name_of_Product.append('-')
    
    try:
        rating=driver.find_element(By.XPATH,"//span[@class='a-size-base a-nowrap']")
        Ratings.append(rating.text.split()[0])

    except:
        Ratings.append('-')
        
          
    try:
        price=driver.find_element(By.XPATH,'//*[@id="corePrice_feature_div"]/div/div/span[1]/span[2]/span[2]')
        Price.append(price.text)

    except:
        Price.append('-')
     
    try:
        exchange=driver.find_element(By.XPATH,'//*[@id="RETURNS_POLICY"]/span/div[2]/span')
        Return_Exchange.append(exchange.text)

    except:
        Return_Exchange.append('-')    
    
        
    try:
        Delivery=driver.find_element(By.XPATH,'//*[@id="mir-layout-DELIVERY_BLOCK-slot-PRIMARY_DELIVERY_MESSAGE_LARGE"]/span/span')
        Expected_Delivery.append(Delivery.text)

    except:
        Expected_Delivery.append('-')
          
                    
    try:
        avail=driver.find_element(By.XPATH,'//*[@id="availability"]/span')
        Availability.append(avail.text)

    except:
        Availability.append('-')
        
        
len(Brand_Name),len(Name_of_Product),len(Ratings),len(Price),len(Return_Exchange),len(Expected_Delivery),len(Availability),len(pages)

(180, 180, 180, 180, 180, 180, 180, 180)

In [9]:
len(Brand_Name),len(Name_of_Product),len(Ratings),len(Price),len(Return_Exchange),len(Expected_Delivery),len(Availability),len(pages)

(180, 180, 180, 180, 180, 180, 180, 180)

In [13]:
data=pd.DataFrame({'Brand Name':Brand_Name,'Name of Product':Name_of_Product,"Ratings":Ratings,"Price":Price,"Return/Exchange":Return_Exchange,"Expected Delivery":Expected_Delivery,"Availability":Availability,"Product URL":pages})
data.index +=1
data

,Brand Name,Name of Product,Ratings,Price,Return/Exchange,Expected Delivery,Availability,Product URL
1,Kadence,"Kadence rosewood Guitar Frontier Series, Elect...",4,"5,499",7 days Replacement,"Friday, 17 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kadence,Kadence Frontier guitar with Online Guitar lea...,4,"4,999",7 days Replacement,"Friday, 17 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,-,ROCKON 41 INCHES ACOUSTIC GUITAR WITH HARD THE...,-,"8,979",7 days Replacement,"Wednesday, 22 November",Only 2 left in stock.,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,VAULT,Vault DA20 Dreadnought Acoustic Guitar With Gi...,4.3,"4,899",7 days Replacement,"Tuesday, 21 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
5,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...",4,"1,999",7 days Replacement,"Tuesday, 21 November",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...,...,...,...
176,PS,PS Signature 41inch Acoustic Guitar (Natural C...,5,"3,599",7 days Replacement,"Wednesday, 22 November",In stock,https://www.amazon.in/PS-Signature-Acoustic-Na...
177,allmusicmart,"“ALL WOODEN” 38” INCH ""BOLT"" Guitar Combo Pack...",-,"2,550",7 days Replacement,-,In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
178,Guitar,GUITAR BRO - COMBO (Black Acoustic Rose Wood G...,3.9,"8,999",7 days Replacement,"Tuesday, 21 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
179,DEVICE,DEVICE OF URBAN INFOTECH 40 inch Acoustic Guit...,1,"5,449",7 days Replacement,"Wednesday, 22 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
180,VAULT,Vault Traveller 34 Inch Acoustic Guitar With T...,3.6,"4,299",7 days Replacement,"Tuesday, 21 November",Only 1 left in stock.,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [11]:
data.to_csv('Question_2.csv', index=True)

In [14]:
time.sleep(2)
driver.close()

# 3.Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [15]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings("ignore")
import time
import keyboard

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

In [16]:
driver = webdriver.Chrome()
driver.get("https://images.google.com/")

In [17]:
time.sleep(2)

try:
    ad=driver.find_element(By.XPATH,'//*[@id="yDmH0d"]/c-wiz/div/div/c-wiz/div/div/div/div[2]/div[2]/button')
    ad.click()
    
except:
    time.sleep(1)
    click=driver.find_element(By.XPATH,'//*[@id="APjFqb"]')
    click.click()

In [18]:
fruit=driver.find_element(By.XPATH,'//*[@id="APjFqb"]')
fruit.send_keys("fruits")

In [19]:
search=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
search.click()

In [20]:
import requests
fruits=[]

image= driver.find_elements(By.XPATH,'//a[@class="iGVLpd kGQAp BqKtob lNHeqe"]')

for i in image[0:10]:
    fruits.append(i.get_attribute("href"))

fruits

                    
for i in range(len(fruits)):
    if i > 11:
        break
    print("Downloading {0} of {1} images" .format(i+1, 10))
    response = requests.get(fruits[i])
    file=open(r'Downloads'+str(i)+".jpg",'wb')
    file.write(response.content)

Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [21]:
search_bar = driver.find_element(By.CLASS_NAME, "og3lId")
search_bar.clear()

click=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
click.click()

car=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
car.send_keys("cars")

In [22]:
time.sleep(1)
search=driver.find_element(By.XPATH,'//div[@class="XZ5MVe"]')
search.click()

In [23]:
import requests
cars=[]

image= driver.find_elements(By.XPATH,'//a[@class="iGVLpd kGQAp BqKtob lNHeqe"]')

for i in image[0:10]:
    cars.append(i.get_attribute("href"))

cars

                    
for i in range(len(cars)):
    if i > 11:
        break
    print("Downloading {0} of {1} images" .format(i+1, 10))
    response = requests.get(cars[i])
    file=open(r'Downloads'+str(i)+".jpg",'wb')
    file.write(response.content)

Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [24]:
search_bar = driver.find_element(By.CLASS_NAME, "og3lId")
search_bar.clear()

click=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
click.click()

car=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
car.send_keys("Meachine Learning")

In [25]:
time.sleep(1)
search=driver.find_element(By.XPATH,'//div[@class="XZ5MVe"]')
search.click()

In [26]:
import requests
machine_learning=[]

image= driver.find_elements(By.XPATH,'//a[@class="iGVLpd kGQAp BqKtob lNHeqe"]')

for i in image[0:10]:
    machine_learning.append(i.get_attribute("href"))

                   
for i in range(len(machine_learning)):
    if i > 11:
        break
    print("Downloading {0} of {1} ML-images" .format(i+1, 10))
    response = requests.get(machine_learning[i])
    file=open(r'Downloads'+str(i)+".jpg",'wb')
    file.write(response.content)

Downloading 1 of 10 ML-images
Downloading 2 of 10 ML-images
Downloading 3 of 10 ML-images
Downloading 4 of 10 ML-images
Downloading 5 of 10 ML-images
Downloading 6 of 10 ML-images
Downloading 7 of 10 ML-images
Downloading 8 of 10 ML-images
Downloading 9 of 10 ML-images
Downloading 10 of 10 ML-images

In [27]:
search_bar = driver.find_element(By.CLASS_NAME, "og3lId")
search_bar.clear()

click=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
click.click()

car=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
car.send_keys("Guitar")

time.sleep(1)
search=driver.find_element(By.XPATH,'//div[@class="XZ5MVe"]')
search.click()

Guitar=[]

image= driver.find_elements(By.XPATH,'//a[@class="iGVLpd kGQAp BqKtob lNHeqe"]')

for i in image[0:10]:
    Guitar.append(i.get_attribute("href"))

                   
for i in range(len(Guitar)):
    if i > 11:
        break
    print("Downloading {0} of {1} guitar images" .format(i+1, 10))
    response = requests.get(Guitar[i])
    file=open(r'Downloads'+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 1 of 10 guitar images
Downloading 2 of 10 guitar images
Downloading 3 of 10 guitar images
Downloading 4 of 10 guitar images
Downloading 5 of 10 guitar images
Downloading 6 of 10 guitar images
Downloading 7 of 10 guitar images
Downloading 8 of 10 guitar images
Downloading 9 of 10 guitar images
Downloading 10 of 10 guitar images

In [29]:
search_bar = driver.find_element(By.CLASS_NAME, "og3lId")
search_bar.clear()

click=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
click.click()

car=driver.find_element(By.XPATH,'//*[@id="REsRA"]')
car.send_keys("Cakes")

time.sleep(1)
search=driver.find_element(By.XPATH,'//div[@class="XZ5MVe"]')
search.click()

Cakes=[]

image= driver.find_elements(By.XPATH,'//a[@class="iGVLpd kGQAp BqKtob lNHeqe"]')

for i in image[0:10]:
    Cakes.append(i.get_attribute("href"))

                   
for i in range(len(Cakes)):
    if i > 11:
        break
    print("Downloading {0} of {1} Cake images" .format(i+1, 10))
    response = requests.get(Cakes[i])
    file=open(r'Downloads'+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 1 of 10 Cake images
Downloading 2 of 10 Cake images
Downloading 3 of 10 Cake images
Downloading 4 of 10 Cake images
Downloading 5 of 10 Cake images
Downloading 6 of 10 Cake images
Downloading 7 of 10 Cake images
Downloading 8 of 10 Cake images
Downloading 9 of 10 Cake images
Downloading 10 of 10 Cake images

In [30]:
time.sleep(2)
driver.close()

# 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. 

Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. 

Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [31]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings("ignore")
import time
import keyboard

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

In [32]:
driver = webdriver.Chrome()
driver.get("https://www.flipkart.com/")
#driver.maximize_window()

In [33]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException

try:
    wait = WebDriverWait(driver, 15)
    element = wait.until(EC.presence_of_element_located((By.CLASS_NAME, 'JFPqaw')))
    notification = driver.find_element(By.CLASS_NAME, "_30XB9F")
    notification.click()
except TimeoutException:
    print("Element not found within 15 seconds")

In [34]:
time.sleep(1)
search=driver.find_element(By.CLASS_NAME,'Pke_EE')
search.send_keys('Samsung Galaxy Note')

In [35]:
searchbutton=driver.find_element(By.CLASS_NAME,'_2iLD__')
searchbutton.click()

In [36]:
Brand_Name = []
Smartphone_name =[]
Colour = []
RAM = []
Storage_ROM = []
Primary_Camera = []
Secondary_Camera = []
Display_Size = []
Battery_Capacity = []
Price = []
Product_URL = []

brandname=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for bn in brandname:
    try:
        Brand_Name.append(bn.text.split()[0])
    except:
        Brand_Name.append('-')
        
smartphone=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for sp in smartphone:
    try:
        Smartphone_name.append(sp.text)
    except:
        Smartphone_name.append("-")
        
color=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for c in color:
    try:
        Colour.append(c.text)
    except:
        Colour.append("-")
        
price=driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for p in price:
    try:
        Price.append(p.text)
    except:
        price.append("-")
        
urls = driver.find_elements(By.XPATH,'//a[@class="_1fQZEK"]')
for u in urls:
    try:
        Product_URL.append(u.get_attribute("href"))
    except:
        Product_URL.append("-")

In [37]:
df1 = pd.DataFrame({'Brand_Name':Brand_Name,'Smartphone_name': Smartphone_name,'Colour':Colour,'Price':Price})

df1['Colour'] = df1['Colour'].str.extract(r'\((.*?)\,')[0].tolist()

df5=pd.DataFrame({'Product_URL':Product_URL})

In [38]:
tags=driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
table=[]

for li in tags:
    item=driver.find_elements(By.XPATH,'//li')
    row=[item.text for item in li.find_elements(By.XPATH,'.//li' )]
    table.append(row)

In [39]:
df2=pd.DataFrame(table)

df2.columns=['RAM|ROM|UPTO','Display_Size ','Primary_Camera|Secondary_Camera','Battery_capacity','Processor','Warranty']
df2.rename(columns={'Storage':0,'Camera':1,'Display':2,'Battery':3,'Processor':4,'Warranty':5,})

df3 = df2['Primary_Camera|Secondary_Camera'].str.split('|', expand=True)
df2['Primary Camera'] = df3[0]
df2['Secondary Camera'] = df3[1]

df2.drop('Primary_Camera|Secondary_Camera', axis=1, inplace=True)
df2.drop('Warranty', axis=1, inplace=True)
df2.drop('Processor', axis=1, inplace=True)

df4=pd.concat([df1,df2,df5],axis=1)
df4.index +=1
df4

,Brand_Name,Smartphone_name,Colour,Price,RAM|ROM|UPTO,Display_Size,Battery_capacity,Primary Camera,Secondary Camera,Product_URL
1,SAMSUNG,"SAMSUNG Galaxy Note 20 (Mystic Green, 256 GB)",Mystic Green,"₹86,000",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,4300 mAh Lithium-ion Battery,64MP + 12MP + 12MP,10MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-2...
2,SAMSUNG,"SAMSUNG Galaxy Note 20 (Mystic Blue, 256 GB)",Mystic Blue,"₹86,000",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,4300 mAh Lithium-ion Battery,64MP + 12MP + 12MP,10MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-2...
3,SAMSUNG,SAMSUNG Galaxy Note 20 Ultra 5G (Mystic Bronze...,Mystic Bronze,"₹1,04,999",12 GB RAM | 256 GB ROM | Expandable Upto 1 TB,17.53 cm (6.9 inch) Quad HD+ Display,4500 mAh Lithium-ion Battery,108MP + 12MP + 12MP,10MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-2...
4,SAMSUNG,"SAMSUNG Galaxy Note 20 Ultra 5G (Mystic Black,...",Mystic Black,"₹99,900",12 GB RAM | 256 GB ROM | Expandable Upto 1 TB,17.53 cm (6.9 inch) Quad HD+ Display,4500 mAh Lithium-ion Battery,108MP + 12MP + 12MP,10MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-2...
5,SAMSUNG,"SAMSUNG Galaxy Note 8 (Orchid Grey, 64 GB)",Orchid Grey,"₹74,000",6 GB RAM | 64 GB ROM | Expandable Upto 256 GB,16.0 cm (6.3 inch) Quad HD+ Display,3300 mAh Battery,12MP + 12MP,8MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-8...
6,SAMSUNG,"SAMSUNG Galaxy Note 8 (Maple Gold, 64 GB)",Maple Gold,"₹74,000",6 GB RAM | 64 GB ROM | Expandable Upto 256 GB,16.0 cm (6.3 inch) Quad HD+ Display,3300 mAh Battery,12MP + 12MP,8MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-8...
7,SAMSUNG,"SAMSUNG Galaxy Note 8 (Midnight Black, 64 GB)",Midnight Black,"₹74,000",6 GB RAM | 64 GB ROM | Expandable Upto 256 GB,16.0 cm (6.3 inch) Quad HD+ Display,3300 mAh Battery,12MP + 12MP,8MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-8...
8,SAMSUNG,"SAMSUNG Galaxy Note 3 (Classic White, 32 GB)",Classic White,"₹43,092",3 GB RAM | 32 GB ROM | Expandable Upto 64 GB,14.48 cm (5.7 inch) Full HD Display,3200 mAh Li-Ion Battery,13MP Rear Camera,2MP Front Camera,https://www.flipkart.com/samsung-galaxy-note-3...

In [40]:
df4.to_csv("Question_4.csv",index=True)

In [41]:
time.sleep(1)
driver.close()

# 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [42]:
import pandas as pd
import selenium
import time
import keyboard
import requests
import regex as re
import warnings
warnings.filterwarnings("ignore")

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

In [43]:
driver=webdriver.Chrome()
driver.get('https://www.google.co.in/maps')

In [44]:
time.sleep(2)
click=driver.find_element(By.XPATH,'//*[@id="searchbox"]')
click.click()

In [45]:
city=driver.find_element(By.XPATH,'//*[@id="searchboxinput"]')
city.send_keys('Agra')

In [46]:
search=driver.find_element(By.XPATH,'//*[@id="searchbox-searchbutton"]')
search.click()
time.sleep(2)

In [49]:
time.sleep(10)
Location=driver.current_url
coordinates=re.findall(r'@(.*)data',Location)

lat_lon=coordinates[0].split(",")
latitude=lat_lon[0]
longitude=lat_lon[1]
print("Latitude:",latitude,'Longitude:',longitude)

Latitude: 27.1763031 Longitude: 77.8976121

In [50]:
time.sleep(1)
driver.close()

# 6.Write a program to scrap all the available details of best gaming laptops from digit.in

For the digits.in question , if you not able to able to get gaming laptops link,

you can scrap Top 10 best laptops in India Instead.

In [51]:
import pandas as pd
import selenium
import time
import keyboard
import requests
import regex as re
import warnings
warnings.filterwarnings("ignore")

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

In [52]:
driver=webdriver.Chrome()
driver.get('https://www.digit.in/')
driver.maximize_window()

In [53]:
driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]").click()

In [54]:
time.sleep(2)
driver.find_element(By.XPATH,"/html/body/div[1]/div[3]/div/div[2]/div[1]/div[3]/div[6]/p").click()

In [55]:
Brand_name=[]
URL=[]

product=driver.find_elements(By.XPATH,'//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
for i in product:
    Brand_name.append(i.text)
    
url=driver.find_elements(By.XPATH,'//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
for i in url:
    URL.append(i.get_attribute("href"))

df=pd.DataFrame({"Brand Name":Brand_name,"URL":URL})
df.index +=1
df.index.name = 'TOP 10 laptop in india'
df

,Brand Name,URL
TOP 10 laptop in india,,
1,Apple MacBook Air 2022 M2 MLY03HN/A,https://www.digit.in/laptops/apple-macbook-air...
2,Samsung Galaxy Book3 Pro 360,https://www.digit.in/laptops/samsung-galaxy-bo...
3,Lenovo Yoga 9i13th Gen Core i7-1360P,https://www.digit.in/laptops/lenovo-yoga-9i13t...
4,Apple MacBook Pro M2 (2023-MPHK3HN/A),https://www.digit.in/laptops/apple-macbook-pro...
5,Dell XPS 13 Plus D560075WIN9S 12th Gen Core i7...,https://www.digit.in/laptops/dell-xps-13-plus-...
6,Acer Swift X SFX16-51G 11th Gen Core i7-11390H,https://www.digit.in/laptops/acer-swift-x-sfx1...

In [56]:
time.sleep(2)
driver.close()

# 7. Write a python program to scrape the details for all billionaires from www.forbes.com. 

Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [57]:
driver=webdriver.Chrome()
driver.get('https://www.forbes.com/')
driver.maximize_window()

In [58]:
driver.find_element(By.XPATH,"/html/body/div[1]/header/nav/div[1]/div[1]/div/div").click()

In [59]:
click=driver.find_element(By.XPATH,"/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[1]/a")
click.click()

In [60]:
time.sleep(5)
search=driver.find_element(By.XPATH,"/html/body/div[1]/div/main/div/section/div[2]/div/div/div[1]/div/div[2]/div/div/a/h2")
search.click()

In [61]:
table = driver.find_element(By.XPATH,"//div[@class='TableRow_rowContainer__IC1Tv']")

In [62]:
data=[]
tags=table.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"]')
for i in tags:
    data.append(i.text)
    
try:
    next_button = driver.find_element(By.XPATH,"//button[@class='pagination-btn pagination-btn--next ']")
    next_button.click()
except:
    pass

len(data)

1400

In [63]:
Rank=data[0::7]
Name=data[1::7]
Net_worth=data[2::7]
Age=data[3::7]
Citizenship=data[4::7]
Source=data[5::7]
Industry=data[6::7]

Top_billionaires=pd.DataFrame({"Rank":Rank, "Name":Name, "Net worth":Net_worth, "Age":Age, "Citizenship":Citizenship, "Source":Source, "Industry":Industry})
Top_billionaires.index += 1
Top_billionaires.index.name="Si No"
Top_billionaires

,Rank,Name,Net worth,Age,Citizenship,Source,Industry
Si No,,,,,,,
1,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail
2,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
3,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
4,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
5,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
196,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
197,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
198,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
199,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
200,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

In [66]:
time.sleep(2)
driver.close()

# 8. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [67]:
import pandas as pd
import selenium
import time
import keyboard
import requests
import regex as re
import warnings
warnings.filterwarnings("ignore")

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

In [68]:
driver=webdriver.Chrome()
driver.get('http://www.youtube.com')
driver.maximize_window()

In [69]:
Videos=driver.find_element(By.XPATH,"/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/form/div[1]/div[1]/input")
Videos.send_keys('hindustani 2')

In [70]:
time.sleep(5)
search=driver.find_element(By.XPATH,"/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/button")
search.click()

In [71]:
time.sleep(5)
video=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a/yt-formatted-string')
video.click()

In [72]:
try:
    time.sleep(25)
    video=driver.find_element(By.XPATH,'//*[@id="ad-text:7"]')
    video.click()
except:
    time.sleep(10)

In [73]:
try:
    time.sleep(5)
    ad=driver.find_element(By.XPATH,'/html/body/ytd-app/ytd-popup-container/tp-yt-paper-dialog/yt-mealbar-promo-renderer/div/div[2]/yt-button-renderer[1]/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]')
    ad.click()
except:
    time.sleep(5)

In [79]:
for i in range(3):
    driver.execute_script("window.scrollBy(0,500)")
    time.sleep(3)

    
for i in range(40):
    driver.execute_script("window.scrollBy(0,5000000)")
    time.sleep(1)

In [80]:
driver.execute_script("window.scrollBy(0,500)")
time.sleep(5)
comments = []
comments_upvote = []
comment_time = []



comment_tag=driver.find_elements(By.XPATH,'//span[@class="style-scope yt-formatted-string"]')
for i in comment_tag[0:500]:
    try:
        comments.append(i.text)
    except:
        comments.append("comments not posted")

        
upvote_tag=driver.find_elements(By.XPATH,'//span[@class="style-scope ytd-comment-action-buttons-renderer"]')
for i in upvote_tag[0:500]:
    try:
        comments_upvote.append(i.text)
    except:
        comments_upvote.append("-")

comment_time_tag=driver.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')
for i in comment_time_tag[0:500]:             
    try:
        comment_time.append(i.text)
    except:
        comment_time.append("-")

In [81]:
len(comments) , len(comments_upvote), len(comment_time)

(500, 500, 500)

In [82]:
df=pd.DataFrame({"Comments":comments,"Comments Upvote":comments_upvote,"Comment Time":comment_time})
df.index +=1
df.index.name = "Si No"
df

,Comments,Comments Upvote,Comment Time
Si No,,,
1,,,10 days ago
2,"2,137",1.5K,4 days ago
3,Comments,,10 days ago
4,only 90s kids know the feeling of seeing kamal...,9,9 days ago
5,Subhash Chandra Bose reference is,,10 days ago
...,...,...,...
496,Ise bolte hain comeback..,,9 days ago
497,,,9 days ago
498,2021- vikram,,9 days ago
499,,,8 days ago
500,2024- hindustani 2,,9 days ago

In [83]:
#empty spces in dataframe meant strings contains spl characters and other 
#languages which is not supported by python

In [84]:
driver.close()

# 9.Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [85]:
import pandas as pd
import selenium
import time
import keyboard
import requests
import regex as re
import warnings
warnings.filterwarnings("ignore")

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

In [86]:
driver=webdriver.Chrome()
driver.get("https://www.hostelworld.com/")
driver.maximize_window()

In [87]:
location=driver.find_element(By.XPATH,'//*[@id="__layout"]/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div/div/div[2]')
location.click()

In [88]:
location_tags=driver.find_element(By.XPATH,'//*[@id="__layout"]/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
location_tags.send_keys('London')

In [89]:
time.sleep(2)
location_tags.send_keys(Keys.TAB)
enter=location_tags.send_keys(Keys.TAB)

In [90]:
search_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]/button')
search_button.click()

In [91]:
search_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button[2]')
search_button.click()

In [92]:
time.sleep(10)
hotel_name=[]
distance=[]
pvt_prices = []
dorms_price = []
rating=[]
review=[]
number_of_review=[]
price=[]


facilities = []
description = []

start=0
end=2

for page in range(start,end):
    try:
        name_tags=driver.find_elements(By.XPATH,'//div[@class="property-name"]/span')
        for i in name_tags:
            hotel_name.append(i.text)
    except NoSuchElementException:
        hostel_name.append('-')
    
    distance_tags=driver.find_elements(By.XPATH,'//div[@class="property-distance"]')
    for i in distance_tags:
        distance.append(i.text.replace("Hostel\n-",""))
    
    
    try:
        rating_tags=driver.find_elements(By.XPATH,'//span[@class="number"]')[1:]
        for i in rating_tags[:60]:
            rating.append(i.text)    
    except NoSuchElementException:
        rating.append('-')
    
    try:
        pvt = driver.find_elements(By.XPATH,'//div[@class="property-accommodation-price"][1]')[1:]
        for i in pvt:
            pvt_prices.append(i.text.replace("\n", "|"))
    except NoSuchElementException:
        pvt_prices.append('-')
        
        
        
    try:
        dorm = driver.find_elements(By.XPATH,'//div[@class="property-accommodation-price"][2]')
        for i in dorm:
            dorms_price.append(i.text.replace("\n", "|"))
    except NoSuchElementException:
        dorms_price.append('-')
    
    try:
        review_tags=driver.find_elements(By.XPATH,'//span[@class="keyword"]')[1:]
        for i in review_tags[:60]:
            review.append(i.text)
    except NoSuchElementException as e:
        print("An exception occurred:", e)
        review.append('-')
        
    number_tags=driver.find_elements(By.XPATH,'//div[@class="review"]')
    for i in number_tags:
        number_of_review.append(i.text)
    
    price_tags=driver.find_elements(By.XPATH,'//div[@class="property-accommodation-prices"]')
    for i  in price_tags:
        price.append(i.text)

In [93]:
print(len(hotel_name),len(distance),len(rating),len(review),len(number_of_review),len(price),len(pvt_prices),len(dorms_price))

60 60 60 60 60 60 60 60

In [94]:
df=pd.DataFrame({'Hotel':hotel_name,'Distance':distance,'Rating':rating,'Overall':review,'Total Review':number_of_review,'Private price':pvt_prices,'Dorms price':dorms_price})
df.index +=1
df

,Hotel,Distance,Rating,Overall,Total Review,Private price,Dorms price
1,St Christopher's Village,1.8km from city centre,8.2,Fabulous,(12630),No Privates Available,"-10%|Dorms From|₹2,364|₹2,128"
2,Onefam Notting Hill,5.5km from city centre,9.6,Superb,(2386),"Privates From|₹17,723","Dorms From|₹5,167"
3,Urbany Hostel London,5.4km from city centre,9.5,Superb,(1013),"Privates From|₹13,628","Dorms From|₹3,351"
4,Generator London,3km from city centre,7.5,Very Good,(7920),"Privates From|₹10,768",No Dorms Available
5,Safestay London Elephant & Castle,1.7km from city centre,7.1,Very Good,(5194),"Privates From|₹9,673","Dorms From|₹1,799"
6,Astor Hyde Park,4.3km from city centre,8.2,Fabulous,(12243),No Privates Available,"Dorms From|₹4,960"
7,NX London Hostel,6.1km from city centre,8.3,Fabulous,(2045),No Privates Available,"Dorms From|₹4,453"
8,Safestay London Kensington Holland Park,5.8km from city centre,6.9,Good,(1718),"-10%|Privates From|₹9,071|₹8,164","-10%|Dorms From|₹1,765|₹1,588"
9,Clink261,3.2km from city centre,8.0,Fabulous,(448),No Privates Available,"Dorms From|₹2,714"
10,No.8 Willesden Hostel London,10km from city centre,7.1,Very Good,(5139),"Privates From|₹3,324","Dorms From|₹1,286"
11,Smart Russell Square Hostel,2.6km from city centre,7.5,Very Good,(10144),No Privates Available,"Dorms From|₹2,317"
12,Destinations Hostels @ The Gallery,1.7km from city centre,9.1,Superb,(275),No Privates Available,"Dorms From|₹4,841"
13,Smart Hyde Park Inn Hostel,5km from city centre,7.6,Very Good,(6766),No Privates Available,"Dorms From|₹2,436"
14,Phoenix Hostel,4.2km from city centre,7.1,Very Good,(4538),No Privates Available,"-5%|Dorms From|₹1,803|₹1,712"
15,No.8 Seven Sisters,9km from city centre,6.5,Good,(4116),No Privates Available,"Dorms From|₹1,065"
16,Hostelle - women only hostel London,5.1km from city centre,8.8,Fabulous,(77),No Privates Available,"Dorms From|₹3,703"
17,YHA London Oxford Street,2.1km from city centre,9.0,Superb,(4673),"Privates From|₹9,172",No Dorms Available
18,St Christopher's Hammersmith,7.5km from city centre,7.6,Very Good,(4340),No Privates Available,"-10%|Dorms From|₹1,987|₹1,788"
19,Prime Backpackers Angel,3.6km from city centre,8.1,Fabulous,(835),No Privates Available,"Dorms From|₹2,751"
20,Barmy Badger Backpackers,5.5km from city centre,9.0,Superb,(2009),"Privates From|₹8,866","Dorms From|₹2,718"
21,London Backpackers,11.9km from city centre,8.0,Fabulous,(4544),"-10%|Privates From|₹6,115|₹5,503","-10%|Dorms From|₹1,800|₹1,620"
22,Astor Victoria,1.8km from city centre,7.1,Very Good,(15056),No Privates Available,"Dorms From|₹1,868"
23,Saint James Backpackers,5.5km from city centre,7.7,Very Good,(1940),"-10%|Privates From|₹7,590|₹6,831","-10%|Dorms From|₹2,684|₹2,415"
24,Kabannas London St Pancras,3.3km from city centre,8.3,Fabulous,(2941),"Privates From|₹11,108","Dorms From|₹3,261"
25,Book a Bed Hostels,6.9km from city centre,7.4,Very Good,(1288),"-10%|Privates From|₹7,460|₹6,714","-10%|Dorms From|₹2,172|₹1,955"
26,St Christopher's Camden,4.3km from city centre,7.4,Very Good,(4104),No Privates Available,"-10%|Dorms From|₹2,056|₹1,850"
27,"PubLove @ The Steam Engine, Waterloo",0.5km from city centre,7.8,Very Good,(436),No Privates Available,"Dorms From|₹4,246"
28,Bell House Hostel,4.2km from city centre,7.1,Very Good,(112),"Privates From|₹5,197","Dorms From|₹2,048"
29,Smart Hyde Park View Hostel,4.8km from city centre,7.7,Very Good,(4730),No Privates Available,"Dorms From|₹2,962"
30,PubLove @ The Rose & Crown,1.6km from city centre,8.3,Fabulous,(214),No Privates Available,"Dorms From|₹5,945"
31,St Christopher's Village,1.8km from city centre,8.2,Fabulous,(12630),No Privates Available,"-10%|Dorms From|₹2,364|₹2,128"
32,Onefam Notting Hill,5.5km from city centre,9.6,Superb,(2386),"Privates From|₹17,723","Dorms From|₹5,167"
33,Urbany Hostel London,5.4km from city centre,9.5,Superb,(1013),"Privates From|₹13,628","Dorms From|₹3,351"
34,Generator London,3km from city centre,7.5,Very Good,(7920),"Privates From|₹10,768",No Dorms Available
35,Safestay London Elephant & Castle,1.7km from city centre,7.1,Very Good,(5194),"Privates From|₹9,673","Dorms From|₹1,799"
36,Astor Hyde Park,4.3km from city centre,8.2,Fabulous,(12243),No Privates Available,"Dorms From|₹4,960"
37,NX London Hostel,6.1km from city centre,8.3,Fabulous,(2045),No Privates Available,"Dorms From|₹4,453"
38,Safestay London Kensington Holland Park,5.8km from city centre,6.9,Good,(1718),"-10%|Privates From|₹9,071|₹8,164","-10%|Dorms From|₹1,765|₹1,588"
39,Clink261,3.2km from city centre,8.0,Fabulous,(448),No Privates Available,"Dorms From|₹2,714"
40,No.8 Willesden Hostel London,10km from city centre,7.1,Very Good,(5139),"Privates From|₹3,324","Dorms From|₹1,286"
41,Smart Russell Square Hostel,2.6km from city centre,7.5,Very Good,(10144),No Privates Available,"Dorms From|₹2,317"
42,Destinations Hostels @ The Gallery,1.7km from city centre,9.1,Superb,(275),No Privates Available,"Dorms From|₹4,841"
43,Smart Hyde Park Inn Hostel,5km from city centre,7.6,Very Good,(6766),No Privates Available,"Dorms From|₹2,436"
44,Phoenix Hostel,4.2km from city centre,7.1,Very Good,(4538),No Privates Available,"-5%|Dorms From|₹1,803|₹1,712"
45,No.8 Seven Sisters,9km from city centre,6.5,Good,(4116),No Privates Available,"Dorms From|₹1,065"
46,Hostelle - women only hostel London,5.1km from city centre,8.8,Fabulous,(77),No Privates Available,"Dorms From|₹3,703"
47,YHA London Oxford Street,2.1km from city centre,9.0,Superb,(4673),"Privates From|₹9,172",No Dorms Available
48,St Christopher's Hammersmith,7.5km from city centre,7.6,Very Good,(4340),No Privates Available,"-10%|Dorms From|₹1,987|₹1,788"
49,Prime Backpackers Angel,3.6km from city centre,8.1,Fabulous,(835),No Privates Available,"Dorms From|₹2,751"
50,Barmy Badger Backpackers,5.5km from city centre,9.0,Superb,(2009),"Privates From|₹8,866","Dorms From|₹2,718"
51,London Backpackers,11.9km from city centre,8.0,Fabulous,(4544),"-10%|Privates From|₹6,115|₹5,503","-10%|Dorms From|₹1,800|₹1,620"
52,Astor Victoria,1.8km from city centre,7.1,Very Good,(15056),No Privates Available,"Dorms From|₹1,868"
53,Saint James Backpackers,5.5km from city centre,7.7,Very Good,(1940),"-10%|Privates From|₹7,590|₹6,831","-10%|Dorms From|₹2,684|₹2,415"
54,Kabannas London St Pancras,3.3km from city centre,8.3,Fabulous,(2941),"Privates From|₹11,108","Dorms From|₹3,261"
55,Book a Bed Hostels,6.9km from city centre,7.4,Very Good,(1288),"-10%|Privates From|₹7,460|₹6,714","-10%|Dorms From|₹2,172|₹1,955"
56,St Christopher's Camden,4.3km from city centre,7.4,Very Good,(4104),No Privates Available,"-10%|Dorms From|₹2,056|₹1,850"
57,"PubLove @ The Steam Engine, Waterloo",0.5km from city centre,7.8,Very Good,(436),No Privates Available,"Dorms From|₹4,246"
58,Bell House Hostel,4.2km from city centre,7.1,Very Good,(112),"Privates From|₹5,197","Dorms From|₹2,048"
59,Smart Hyde Park View Hostel,4.8km from city centre,7.7,Very Good,(4730),No Privates Available,"Dorms From|₹2,962"
60,PubLove @ The Rose & Crown,1.6km from city centre,8.3,Fabulous,(214),No Privates Available,"Dorms From|₹5,945"

In [95]:
time.sleep(2)
driver.close()

In [96]:
##Thank you##